const resList = [
  {
    id: 1,
    name: 'Spicy Treats',
    cuisines: ['Indian', 'Mughlai'],
    delivery_time: '30 mins',
    star_ratings: 4.5,
    cost: 500,
    image_url: 'https://example.com/images/spicy_treats.jpg',
  },
  {
    id: 2,
    name: 'Tandoori Nights',
    cuisines: ['North Indian', 'BBQ'],
    delivery_time: '40 mins',
    star_ratings: 4.3,
    cost: 700,
    image_url: 'https://example.com/images/tandoori_nights.jpg',
  },
  {
    id: 3,
    name: 'Sushi Delight',
    cuisines: ['Japanese', 'Asian'],
    delivery_time: '50 mins',
    star_ratings: 4.8,
    cost: 1200,
    image_url: 'https://example.com/images/sushi_delight.jpg',
  },
  {
    id: 4,
    name: 'Burger Mania',
    cuisines: ['American', 'Fast Food'],
    delivery_time: '25 mins',
    star_ratings: 4.2,
    cost: 400,
    image_url: 'https://example.com/images/burger_mania.jpg',
  },
  {
    id: 5,
    name: 'Pasta Paradise',
    cuisines: ['Italian', 'Continental'],
    delivery_time: '35 mins',
    star_ratings: 4.6,
    cost: 600,
    image_url: 'https://example.com/images/pasta_paradise.jpg',
  },
  {
    id: 6,
    name: 'Biryani Express',
    cuisines: ['Hyderabadi', 'Indian'],
    delivery_time: '45 mins',
    star_ratings: 4.7,
    cost: 800,
    image_url: 'https://example.com/images/biryani_express.jpg',
  },
  {
    id: 7,
    name: 'Vegan Delights',
    cuisines: ['Vegan', 'Healthy'],
    delivery_time: '30 mins',
    star_ratings: 4.5,
    cost: 550,
    image_url: 'https://example.com/images/vegan_delights.jpg',
  },
  {
    id: 8,
    name: 'South Spice',
    cuisines: ['South Indian', 'Chettinad'],
    delivery_time: '40 mins',
    star_ratings: 4.4,
    cost: 650,
    image_url: 'https://example.com/images/south_spice.jpg',
  },
  {
    id: 9,
    name: 'Thai Aroma',
    cuisines: ['Thai', 'Asian'],
    delivery_time: '50 mins',
    star_ratings: 4.6,
    cost: 1100,
    image_url: 'https://example.com/images/thai_aroma.jpg',
  },
  {
    id: 10,
    name: 'Punjabi Zaika',
    cuisines: ['Punjabi', 'Indian'],
    delivery_time: '35 mins',
    star_ratings: 4.3,
    cost: 700,
    image_url: 'https://example.com/images/punjabi_zaika.jpg',
  },
  {
    id: 11,
    name: 'The Steak House',
    cuisines: ['American', 'BBQ'],
    delivery_time: '45 mins',
    star_ratings: 4.7,
    cost: 1500,
    image_url: 'https://example.com/images/the_steak_house.jpg',
  },
  {
    id: 12,
    name: 'Dim Sum Corner',
    cuisines: ['Chinese', 'Asian'],
    delivery_time: '40 mins',
    star_ratings: 4.6,
    cost: 900,
    image_url: 'https://example.com/images/dim_sum_corner.jpg',
  },
  {
    id: 13,
    name: 'Mexican Fiesta',
    cuisines: ['Mexican', 'Tex-Mex'],
    delivery_time: '30 mins',
    star_ratings: 4.2,
    cost: 600,
    image_url: 'https://example.com/images/mexican_fiesta.jpg',
  },
  {
    id: 14,
    name: 'Wrap & Roll',
    cuisines: ['Fast Food', 'Street Food'],
    delivery_time: '20 mins',
    star_ratings: 4.0,
    cost: 350,
    image_url: 'https://example.com/images/wrap_roll.jpg',
  },
  {
    id: 15,
    name: 'Mediterranean Bites',
    cuisines: ['Mediterranean', 'Greek'],
    delivery_time: '40 mins',
    star_ratings: 4.5,
    cost: 850,
    image_url: 'https://example.com/images/mediterranean_bites.jpg',
  },
  {
    id: 16,
    name: 'Dessert Heaven',
    cuisines: ['Desserts', 'Bakery'],
    delivery_time: '25 mins',
    star_ratings: 4.9,
    cost: 450,
    image_url: 'https://example.com/images/dessert_heaven.jpg',
  },
  {
    id: 17,
    name: 'Seafood Bay',
    cuisines: ['Seafood', 'Continental'],
    delivery_time: '50 mins',
    star_ratings: 4.8,
    cost: 1300,
    image_url: 'https://example.com/images/seafood_bay.jpg',
  },
  {
    id: 18,
    name: 'Street Chaat',
    cuisines: ['Indian', 'Street Food'],
    delivery_time: '20 mins',
    star_ratings: 4.1,
    cost: 300,
    image_url: 'https://example.com/images/street_chaat.jpg',
  },
];

export default resList;
